In [1]:
import cv2
import numpy as np
from math import acos, pi, sqrt, cos, e, atan

In [2]:
def get_Px_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for y in range(filter_size):
        filter[y][0] = -1
        filter[y][1] = 0
        filter[y][2] = 1
    return filter


def Px_filtering(src, filter_size):
    Px = np.zeros(shape=(src.shape))
    Px_filter = get_Px_filter(filter_size)
    #print(Px_filter)
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Px[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Px_filter[j][i]
    Px = np.array(np.round(Px), dtype=np.uint8)
    return Px
    

In [3]:
def get_Py_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for x in range(filter_size):
        filter[0][x] = 1
        filter[1][x] = 0
        filter[2][x] = -1
    return filter


def Py_filtering(src, filter_size):
    Py = np.zeros(shape=(src.shape))
    Py_filter = get_Py_filter(filter_size)
    #print(Py_filter)
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Py[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Py_filter[j][i]
    Py = np.array(np.round(Py), dtype=np.uint8)
    return Py
    

In [4]:
def get_Px_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for y in range(filter_size):
        filter[y][0] = -1
        filter[y][1] = 0
        filter[y][2] = 1
    return filter

def get_Py_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for x in range(filter_size):
        filter[0][x] = 1
        filter[1][x] = 0
        filter[2][x] = -1
    return filter


def prewitt_filtering(src, filter_size):
    Px = np.zeros(shape=(src.shape))
    Py = np.zeros(shape=(src.shape))
    Prewitt = np.zeros(shape=(src.shape))
    
    Px_filter = get_Px_filter(filter_size)
    Py_filter = get_Py_filter(filter_size)
    
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Py[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Py_filter[j][i]
                    Px[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Px_filter[j][i]
            Prewitt[y][x] = ((Px[y][x])**2 + (Py[y][x])**2)**0.5
    
    
    Prewitt = np.array(np.round(Prewitt), dtype=np.uint8)
    return Prewitt

In [5]:
def get_Sx_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for y in range(filter_size):
        filter[y][0] = -1
        filter[y][1] = 0
        filter[y][2] = 1
        
    for x in range(filter_size):
        filter[1][x] *= 2
    return filter


def Sx_filtering(src, filter_size):
    Sx = np.zeros(shape=(src.shape))
    Sx_filter = get_Sx_filter(filter_size)
    print(Sx_filter)
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Sx[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Sx_filter[j][i]
    Sx = np.array(np.round(Sx), dtype=np.uint8)
    return Sx
    

In [6]:
def get_Sy_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for x in range(filter_size):
        filter[0][x] = 1
        filter[1][x] = 0
        filter[2][x] = -1
        
    for y in range(filter_size):
        filter[y][1] *= 2
    return filter


def Sy_filtering(src, filter_size):
    Sy = np.zeros(shape=(src.shape))
    Sy_filter = get_Sy_filter(filter_size)
    print(Sy_filter)
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Sy[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Sy_filter[j][i]
    Sy = np.array(np.round(Sy), dtype=np.uint8)
    return Sy
    

In [7]:
def get_Sx_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for y in range(filter_size):
        filter[y][0] = -1
        filter[y][1] = 0
        filter[y][2] = 1
    
    for x in range(filter_size):
        filter[1][x] *= 2
    return filter

def get_Sy_filter(filter_size):
    filter = np.zeros(shape=(filter_size, filter_size))
    for x in range(filter_size):
        filter[0][x] = 1
        filter[1][x] = 0
        filter[2][x] = -1
        
    for y in range(filter_size):
        filter[y][1] *= 2
    return filter


def sobel_filtering(src, filter_size):
    Sx = np.zeros(shape=(src.shape))
    Sy = np.zeros(shape=(src.shape))
    Sobel = np.zeros(shape=(src.shape))
    
    Sx_filter = get_Sx_filter(filter_size)
    Sy_filter = get_Sy_filter(filter_size)
    
    for y in range(int(filter_size/2), src.shape[0]-int(filter_size/2)):
        for x in range(int(filter_size/2), src.shape[1]-int(filter_size/2)):
            for j in range(filter_size):
                for i in range(filter_size):
                    Sy[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Sy_filter[j][i]
                    Sx[y][x] += src[y-int(filter_size/2)+j][x-int(filter_size/2)+i] * Sx_filter[j][i]
            Sobel[y][x] = ((Sx[y][x])**2 + (Sy[y][x])**2)**0.5
    
    Sobel = np.array(np.round(Sobel), dtype=np.uint8)
    return Sobel

In [13]:
src = cv2.imread('./test image/butterfly.jpg', cv2.IMREAD_GRAYSCALE)
Px = Px_filtering(src,3)
Py = Py_filtering(src,3)
Prewitt = prewitt_filtering(src,3)
ret, Prewitt_Threshold = cv2.threshold(Prewitt,127,255,cv2.THRESH_BINARY)

Sx = Sx_filtering(src,3)
Sy = Sy_filtering(src,3)
Sobel = sobel_filtering(src,3)
ret, Sobel_Threshold = cv2.threshold(Sobel,127,255,cv2.THRESH_BINARY)

cv2.imshow("src", src)
cv2.imshow("Prewitt X", Px)
cv2.imshow("Prewitt Y", Py)
cv2.imshow("Prewitt", Prewitt)
cv2.imshow("Prewitt_Threshold", Prewitt_Threshold)

cv2.imshow("Sobel X", Sx)
cv2.imshow("Sobel Y", Sy)
cv2.imshow("Sobel", Sobel)
cv2.imshow("Sobel_Threshold", Sobel_Threshold)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[-1.  0.  1.]
 [-2.  0.  2.]
 [-1.  0.  1.]]
[[ 1.  2.  1.]
 [ 0.  0.  0.]
 [-1. -2. -1.]]
